### ISSUE TITLE
How to install on Mac without docker

### ISSUE THREAD

**Issue by ssabnis** [hi-primus/bumblebee#108]
How can I install on Mac without Docker>

**Comment by luis11011** [comment]
Hi,

Right now we are working on other Issues, deploying on Mac is not a priority, but you could try to follow the steps of [this tutorial](https://medium.com/hi-bumblebee/how-to-install-bumblebee-on-digital-ocean-ef77138f1838). Basically you'll need to install Optimus trough the repo using PIP, Jupyter Kernel Gateway, Node and Mongo.

If you manage to record the steps that could help us in the future. Thanks!

**Comment by argenisleon** [comment]
Hi @ssabnis,

Did the tutorial work for you?

**Comment by argenisleon** [comment]
If you need help please feel free to create another issue.
