### ISSUE TITLE
Add string grouper clustering algorithm

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/bumblebee#57]
Right now Optimus handle fingerprints, ngram-fingerprint, Levenstein distance to cluster strings. Using the string grouper library could give a boost to the clustering Related to https://github.com/ironmussa/Optimus/issues/919

**Comment by luis11011** [comment]
Included Fingerprint, N-gram fingerprint, Metaphone, Nysiis, Match Rating Approach, Double Metaphone, Soundex and Levenshtein.
