### ISSUE TITLE
Improve UI/UX for data source handling

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/bumblebee#60]
Menu "add data source"
- [x] Add from file
- [x] Add from database
- [ ] Add from a loaded data source
- [ ] Manage data sources

Menu "save"
- [x] Download
- [x] Save to database

UX
- [x] Add data source call to action when opening a new tab
- [x] Open the load dataset dialog when opening a new tab
- [ ] Show more recent data sources
- [x] Drag and drop from file

**Comment by argenisleon** [comment]
@luis11011  to connecto to a  database you can test a connection using:

```
db =  op.connect(
    driver="mysql",
    host="165.227.196.70", 
    database= "optimus", 
    user= "test", 
    password = "test")
```

to get a dataframe `db.table_to_df("test_data")`. After that you can handle the dataframe as usual

**Comment by luis11011** [comment]
Data sources managing outside of a workspace are no longer a priority so I'm closing this.
