### ISSUE TITLE
[FEA] Plugin Arquitecture

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/bumblebee#62]
Taking with @luis11011 we are planning to let users install plugins. These plugins will add an extra button to the UI so the user can get additional functionality like for example imputing data, time series analysis, or geospatial processing.

For this we have to define:
- [x] Plugins types. @luis11011 can you expand this point in the comments?
- [x] Define how Bumblebee will interact with the plugin.
- [x] Define the python plugin structure.
- [x] Backend considerations @EdoGp

**Comment by argenisleon** [comment]
After a video conversation with @luis11011:

## Plugins types
We defined two plugin types:

1. A plug-in in which the user can define user/python input and the function implementation in python. 
2. A plug-in that inlines some python code.

**Consideration**
A plugin can be designed specifically for an engine. For example, a user could write a plugin to run only for `cudf` or may for only a couple of engines like cuDF or dask_cuDF.

## Define how Bumblebee will interact with the plugin
* Only a user with Admin Roles could install plugins
* We are defining if the plugin can be used for a specific user or for projects.

##  Define the python plugin structure
A `.json` file with the structure.
```json
custom: {
      "name": "Custom Function test",
      "fields": {
          "name": {
              "name": "Name",
              "default": "",
              "empty": false,
              "type": "string"
          }
      },
      "code": "# {{payload.name[0]}} {{payload['name'][1]}}"
    }
```
## Backend considerations
### Uploading
A plugin should be encapsulated in a JSON file and should be uploaded from the Bumblebee UI. Only users with Admin roles can upload plugins.

### Permission
The admin user can define in which workspaces the plugin will be available.

@luis11011 I am going to create a .md file to explain how can a developer write a plugin.

**Comment by luis11011** [comment]
Implementing this feature using repositories, here's an example https://github.com/primus-forge/ml-operations
