### ISSUE TITLE
Improve concat UX operations

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/bumblebee#90]
After taking with @luis11011 we decide to make these improvements to the concat operation:

- [x] Move from the sidebar to Fullscreen
- [x] Remove column using an x button inside
- [x] Search a column from the placeholder
- [x] Add the dataframe name at the top
- [ ] Show an operation preview at the bottom of the windows
- [ ] Use color for every dataframe in the preview table so the user can easily identify the result

**Comment by luis11011** [comment]
A different approach for the preview was approached, I'm closing this.
